### ISSUE TITLE
Configurar Dependências no pubspec.yaml

### ISSUE THREAD

**Issue by Rodrigosdk** [Rodrigosdk/FinMind#2]
**Descrição:**
Adicionar todas as dependências necessárias para o desenvolvimento inicial do projeto.

**Tarefas:**

* Adicionar as seguintes dependências:

```yaml
dependencies:
  flutter_bloc: ^9.1.1
  go_router: ^15.1.2
  dio: ^5.8.0+1
  objectbox: ^4.2.0
  get_it: ^8.0.3
  injectable: ^2.5.0
```

**Critérios de Aceitação:**

* Executar `flutter pub get` sem erros.
